services:
  - type: web
    name: rasoimitra-api
    runtime: docker
    plan: starter
    region: singapore
    dockerfilePath: ./Dockerfile
    dockerContext: .
    healthCheckPath: /health
    autoDeploy: true
    envVars:
      - key: ASPNETCORE_ENVIRONMENT
        value: Production
      - key: Swagger__Switch
        value: "Y"
